/*
 * Copyright (c) 2025. Marcel Van Heerwaarden
 * @Author Marcel van Heerwaarden
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */

package com.github.mheerwaarden.eventdemo.ui.util

import androidx.compose.ui.graphics.Color

// See https://www.w3schools.com/colors/colors_names.asp
enum class HtmlColors(
    val text: String, 
    val argb: Long,
) {
    ALICE_BLUE("Alice Blue", 0xFFF0F8FF),
    ANTIQUE_WHITE("Antique White",0xFFFAEBD7),
    AQUA("Aqua",0xFF00FFFF),
    AQUAMARINE("Aquamarine",0xFF7FFFD4),
    AZURE("Azure",0xFFF0FFFF),
    BEIGE("Beige",0xFFF5F5DC),
    BISQUE("Bisque",0xFFFFE4C4),
    BLACK("Black",0xFF000000),
    BLANCHED_ALMOND("Blanched Almond",0xFFFFEBCD),
    BLUE("Blue",0xFF0000FF),
    BLUE_VIOLET("Blue Violet",0xFF8A2BE2),
    BROWN("Brown",0xFFA52A2A),
    BURLY_WOOD("Burly Wood",0xFFDEB887),
    CADET_BLUE("Cadet Blue",0xFF5F9EA0),
    CHARTREUSE("Chartreuse",0xFF7FFF00),
    CHOCOLATE("Chocolate",0xFFD2691E),
    CORAL("Coral",0xFFFF7F50),
    CORNFLOWER_BLUE("Cornflower Blue",0xFF6495ED),
    CORNSILK("Cornsilk",0xFFFFF8DC),
    CRIMSON("Crimson",0xFFDC143C),
    CYAN("Cyan",0xFF00FFFF),
    DARK_BLUE("Dark Blue",0xFF00008B),
    DARK_CYAN("Dark Cyan",0xFF008B8B),
    DARK_GOLDEN_ROD("Dark Golden Rod",0xFFB8860B),
    DARK_GRAY("Dark Gray",0xFFA9A9A9),
    DARK_GREY("Dark Grey",0xFFA9A9A9),
    DARK_GREEN("Dark Green",0xFF006400),
    DARK_KHAKI("Dark Khaki",0xFFBDB76B),
    DARK_MAGENTA("Dark Magenta",0xFF8B008B),
    DARK_OLIVE_GREEN("Dark Olive Green",0xFF556B2F),
    DARK_ORANGE("Dark Orange",0xFFFF8C00),
    DARK_ORCHID("Dark Orchid",0xFF9932CC),
    DARK_RED("Dark Red",0xFF8B0000),
    DARK_SALMON("Dark Salmon",0xFFE9967A),
    DARK_SEA_GREEN("Dark Sea Green",0xFF8FBC8F),
    DARK_SLATE_BLUE("Dark Slate Blue",0xFF483D8B),
    DARK_SLATE_GRAY("Dark Slate Gray",0xFF2F4F4F),
    DARK_SLATE_GREY("Dark Slate Grey",0xFF2F4F4F),
    DARK_TURQUOISE("Dark Turquoise",0xFF00CED1),
    DARK_VIOLET("Dark Violet",0xFF9400D3),
    DEEP_PINK("Deep Pink",0xFFFF1493),
    DEEP_SKY_BLUE("Deep Sky Blue",0xFF00BFFF),
    DIM_GRAY("Dim Gray",0xFF696969),
    DIM_GREY("Dim Grey",0xFF696969),
    DODGER_BLUE("Dodger Blue",0xFF1E90FF),
    FIRE_BRICK("Fire Brick",0xFFB22222),
    FLORAL_WHITE("Floral White",0xFFFFFAF0),
    FOREST_GREEN("Forest Green",0xFF228B22),
    FUCHSIA("Fuchsia",0xFFFF00FF),
    GAINSBORO("Gainsboro",0xFFDCDCDC),
    GHOST_WHITE("Ghost White",0xFFF8F8FF),
    GOLD("Gold",0xFFFFD700),
    GOLDEN_ROD("Golden Rod",0xFFDAA520),
    GRAY("Gray",0xFF808080),
    GREY("Grey",0xFF808080),
    GREEN("Green",0xFF008000),
    GREEN_YELLOW("Green Yellow",0xFFADFF2F),
    HONEY_DEW("Honey Dew",0xFFF0FFF0),
    HOT_PINK("Hot Pink",0xFFFF69B4),
    INDIAN_RED("Indian Red",0xFFCD5C5C),
    INDIGO("Indigo",0xFF4B0082),
    IVORY("Ivory",0xFFFFFFF0),
    KHAKI("Khaki",0xFFF0E68C),
    LAVENDER("Lavender",0xFFE6E6FA),
    LAVENDER_BLUSH("Lavender Blush",0xFFFFF0F5),
    LAWN_GREEN("Lawn Green",0xFF7CFC00),
    LEMON_CHIFFON("Lemon Chiffon",0xFFFFFACD),
    LIGHT_BLUE("Light Blue",0xFFADD8E6),
    LIGHT_CORAL("Light Coral",0xFFF08080),
    LIGHT_CYAN("Light Cyan",0xFFE0FFFF),
    LIGHT_GOLDEN_ROD_YELLOW("Light Golden Rod Yellow",0xFFFAFAD2),
    LIGHT_GRAY("Light Gray",0xFFD3D3D3),
    LIGHT_GREY("Light Grey",0xFFD3D3D3),
    LIGHT_GREEN("Light Green",0xFF90EE90),
    LIGHT_PINK("Light Pink",0xFFFFB6C1),
    LIGHT_SALMON("Light Salmon",0xFFFFA07A),
    LIGHT_SEA_GREEN("Light Sea Green",0xFF20B2AA),
    LIGHT_SKY_BLUE("Light Sky Blue",0xFF87CEFA),
    LIGHT_SLATE_GRAY("Light Slate Gray",0xFF778899),
    LIGHT_SLATE_GREY("Light Slate Grey",0xFF778899),
    LIGHT_STEEL_BLUE("Light Steel Blue",0xFFB0C4DE),
    LIGHT_YELLOW("Light Yellow",0xFFFFFFE0),
    LIME("Lime",0xFF00FF00),
    LIME_GREEN("Lime Green",0xFF32CD32),
    LINEN("Linen",0xFFFAF0E6),
    MAGENTA("Magenta",0xFFFF00FF),
    MAROON("Maroon",0xFF800000),
    MEDIUM_AQUA_MARINE("Medium Aqua Marine",0xFF66CDAA),
    MEDIUM_BLUE("Medium Blue",0xFF0000CD),
    MEDIUM_ORCHID("Medium Orchid",0xFFBA55D3),
    MEDIUM_PURPLE("Medium Purple",0xFF9370DB),
    MEDIUM_SEA_GREEN("Medium Sea Green",0xFF3CB371),
    MEDIUM_SLATE_BLUE("Medium Slate Blue",0xFF7B68EE),
    MEDIUM_SPRING_GREEN("Medium Spring Green",0xFF00FA9A),
    MEDIUM_TURQUOISE("Medium Turquoise",0xFF48D1CC),
    MEDIUM_VIOLET_RED("Medium Violet Red",0xFFC71585),
    MIDNIGHT_BLUE("Midnight Blue",0xFF191970),
    MINT_CREAM("Mint Cream",0xFFF5FFFA),
    MISTY_ROSE("Misty Rose",0xFFFFE4E1),
    MOCCASIN("Moccasin",0xFFFFE4B5),
    NAVAJO_WHITE("Navajo White",0xFFFFDEAD),
    NAVY("Navy",0xFF000080),
    OLD_LACE("Old Lace",0xFFFDF5E6),
    OLIVE("Olive",0xFF808000),
    OLIVE_DRAB("Olive Drab",0xFF6B8E23),
    ORANGE("Orange",0xFFFFA500),
    ORANGE_RED("Orange Red",0xFFFF4500),
    ORCHID("Orchid",0xFFDA70D6),
    PALE_GOLDEN_ROD("Pale Golden Rod",0xFFEEE8AA),
    PALE_GREEN("Pale Green",0xFF98FB98),
    PALE_TURQUOISE("Pale Turquoise",0xFFAFEEEE),
    PALE_VIOLET_RED("Pale Violet Red",0xFFDB7093),
    PAPAYA_WHIP("Papaya Whip",0xFFFFEFD5),
    PEACH_PUFF("Peach Puff",0xFFFFDAB9),
    PERU("Peru",0xFFCD853F),
    PINK("Pink",0xFFFFC0CB),
    PLUM("Plum",0xFFDDA0DD),
    POWDER_BLUE("Powder Blue",0xFFB0E0E6),
    PURPLE("Purple",0xFF800080),
    REBECCA_PURPLE("Rebecca Purple",0xFF663399),
    RED("Red",0xFFFF0000),
    ROSY_BROWN("Rosy Brown",0xFFBC8F8F),
    ROYAL_BLUE("Royal Blue",0xFF4169E1),
    SADDLE_BROWN("Saddle Brown",0xFF8B4513),
    SALMON("Salmon",0xFFFA8072),
    SANDY_BROWN("Sandy Brown",0xFFF4A460),
    SEA_GREEN("Sea Green",0xFF2E8B57),
    SEA_SHELL("Sea Shell",0xFFFFF5EE),
    SIENNA("Sienna",0xFFA0522D),
    SILVER("Silver",0xFFC0C0C0),
    SKY_BLUE("Sky Blue",0xFF87CEEB),
    SLATE_BLUE("Slate Blue",0xFF6A5ACD),
    SLATE_GRAY("Slate Gray",0xFF708090),
    SLATE_GREY("Slate Grey",0xFF708090),
    SNOW("Snow",0xFFFFFAFA),
    SPRING_GREEN("Spring Green",0xFF00FF7F),
    STEEL_BLUE("Steel Blue",0xFF4682B4),
    TAN("Tan",0xFFD2B48C),
    TEAL("Teal",0xFF008080),
    THISTLE("Thistle",0xFFD8BFD8),
    TOMATO("Tomato",0xFFFF6347),
    TURQUOISE("Turquoise",0xFF40E0D0),
    VIOLET("Violet",0xFFEE82EE),
    WHEAT("Wheat",0xFFF5DEB3),
    WHITE("White",0xFFFFFFFF),
    WHITE_SMOKE("White Smoke",0xFFF5F5F5),
    YELLOW("Yellow",0xFFFFFF00),
    YELLOW_GREEN("Yellow Green",0xFF9ACD32);

    val color: Color = Color(argb)
}